import sharp from "sharp";
import * as fs from "fs";
import * as path from "path";

const TILE = 16;
const COLS = 4;

interface TextureDef {
  name: string;
  color: string;
  split?: { topColor: string; bottomColor: string };
}

const TEXTURES: TextureDef[] = [
  { name: "grass_top", color: "#4CAF50" },
  { name: "grass_side", color: "", split: { topColor: "#4CAF50", bottomColor: "#8D6E63" } },
  { name: "dirt", color: "#8D6E63" },
  { name: "stone", color: "#9E9E9E" },
  { name: "sand", color: "#FDD835" },
  { name: "log_side", color: "#5D4037" },
  { name: "log_top", color: "#D7CCC8" },
  { name: "leaves", color: "#2E7D32" },
  { name: "crystal_shard", color: "#00E5FF" },
];

function hexToRGB(hex: string): { r: number; g: number; b: number } {
  const n = parseInt(hex.replace("#", ""), 16);
  return { r: (n >> 16) & 255, g: (n >> 8) & 255, b: n & 255 };
}

function solidTile(hex: string): Buffer {
  const { r, g, b } = hexToRGB(hex);
  const buf = Buffer.alloc(TILE * TILE * 4);
  for (let i = 0; i < TILE * TILE; i++) {
    buf[i * 4] = r;
    buf[i * 4 + 1] = g;
    buf[i * 4 + 2] = b;
    buf[i * 4 + 3] = 255;
  }
  return buf;
}

function splitTile(topHex: string, bottomHex: string): Buffer {
  const top = hexToRGB(topHex);
  const bot = hexToRGB(bottomHex);
  const buf = Buffer.alloc(TILE * TILE * 4);
  const half = TILE / 2;
  for (let y = 0; y < TILE; y++) {
    const c = y < half ? top : bot;
    for (let x = 0; x < TILE; x++) {
      const i = (y * TILE + x) * 4;
      buf[i] = c.r;
      buf[i + 1] = c.g;
      buf[i + 2] = c.b;
      buf[i + 3] = 255;
    }
  }
  return buf;
}

async function main() {
  const rows = Math.ceil(TEXTURES.length / COLS);
  const atlasW = COLS * TILE;
  const atlasH = rows * TILE;

  // Build atlas pixel buffer
  const atlasBuf = Buffer.alloc(atlasW * atlasH * 4);

  const uvs: Record<string, { u0: number; v0: number; u1: number; v1: number }> = {};

  for (let i = 0; i < TEXTURES.length; i++) {
    const tex = TEXTURES[i];
    const col = i % COLS;
    const row = Math.floor(i / COLS);

    const tile = tex.split
      ? splitTile(tex.split.topColor, tex.split.bottomColor)
      : solidTile(tex.color);

    // Copy tile into atlas buffer
    for (let y = 0; y < TILE; y++) {
      for (let x = 0; x < TILE; x++) {
        const srcIdx = (y * TILE + x) * 4;
        const dstIdx = ((row * TILE + y) * atlasW + (col * TILE + x)) * 4;
        atlasBuf[dstIdx] = tile[srcIdx];
        atlasBuf[dstIdx + 1] = tile[srcIdx + 1];
        atlasBuf[dstIdx + 2] = tile[srcIdx + 2];
        atlasBuf[dstIdx + 3] = tile[srcIdx + 3];
      }
    }

    uvs[tex.name] = {
      u0: (col * TILE) / atlasW,
      v0: (row * TILE) / atlasH,
      u1: ((col + 1) * TILE) / atlasW,
      v1: ((row + 1) * TILE) / atlasH,
    };
  }

  // Write atlas PNG
  const outDir = path.resolve(__dirname, "../public/textures");
  fs.mkdirSync(outDir, { recursive: true });
  await sharp(atlasBuf, { raw: { width: atlasW, height: atlasH, channels: 4 } })
    .png()
    .toFile(path.join(outDir, "atlas.png"));
  console.log(`Atlas written to public/textures/atlas.png (${atlasW}x${atlasH})`);

  // Write UV TypeScript file
  const uvFile = path.resolve(__dirname, "../src/data/atlasUVs.ts");
  const lines = [
    "/** Auto-generated by scripts/buildAtlas.ts. Do not edit manually. */",
    "export const ATLAS_UVS: Record<string, { u0: number; v0: number; u1: number; v1: number }> = {",
  ];
  for (const [name, rect] of Object.entries(uvs)) {
    lines.push(`  ${name}: { u0: ${rect.u0}, v0: ${rect.v0}, u1: ${rect.u1}, v1: ${rect.v1} },`);
  }
  lines.push("};");
  lines.push("");
  fs.writeFileSync(uvFile, lines.join("\n"));
  console.log(`UV data written to src/data/atlasUVs.ts (${Object.keys(uvs).length} entries)`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
