/** Auto-generated by scripts/buildAtlas.ts. Do not edit manually. */
export const ATLAS_HASH = "573db3f7";
export const ATLAS_UVS: Record<string, { u0: number; v0: number; u1: number; v1: number }> = {
  grass_top: { u0: 0, v0: 0, u1: 0.25, v1: 0.2 },
  grass_side: { u0: 0.25, v0: 0, u1: 0.5, v1: 0.2 },
  dirt: { u0: 0.5, v0: 0, u1: 0.75, v1: 0.2 },
  stone: { u0: 0.75, v0: 0, u1: 1, v1: 0.2 },
  sand: { u0: 0, v0: 0.2, u1: 0.25, v1: 0.4 },
  log_side: { u0: 0.25, v0: 0.2, u1: 0.5, v1: 0.4 },
  log_top: { u0: 0.5, v0: 0.2, u1: 0.75, v1: 0.4 },
  leaves: { u0: 0.75, v0: 0.2, u1: 1, v1: 0.4 },
  crystal_shard: { u0: 0, v0: 0.4, u1: 0.25, v1: 0.6 },
  planks: { u0: 0.25, v0: 0.4, u1: 0.5, v1: 0.6 },
  crafting_table_top: { u0: 0.5, v0: 0.4, u1: 0.75, v1: 0.6 },
  crafting_table_side: { u0: 0.75, v0: 0.4, u1: 1, v1: 0.6 },
  furnace_top: { u0: 0, v0: 0.6, u1: 0.25, v1: 0.8 },
  furnace_side: { u0: 0.25, v0: 0.6, u1: 0.5, v1: 0.8 },
  iron_ore: { u0: 0.5, v0: 0.6, u1: 0.75, v1: 0.8 },
  diamond_ore: { u0: 0.75, v0: 0.6, u1: 1, v1: 0.8 },
  lava: { u0: 0, v0: 0.8, u1: 0.25, v1: 1 },
  water: { u0: 0.25, v0: 0.8, u1: 0.5, v1: 1 },
  snow: { u0: 0.5, v0: 0.8, u1: 0.75, v1: 1 },
  ice: { u0: 0.75, v0: 0.8, u1: 1, v1: 1 },
};
