/** Auto-generated by scripts/buildAtlas.ts. Do not edit manually. */
export const ATLAS_UVS: Record<string, { u0: number; v0: number; u1: number; v1: number }> = {
  grass_top: { u0: 0, v0: 0, u1: 0.25, v1: 0.25 },
  grass_side: { u0: 0.25, v0: 0, u1: 0.5, v1: 0.25 },
  dirt: { u0: 0.5, v0: 0, u1: 0.75, v1: 0.25 },
  stone: { u0: 0.75, v0: 0, u1: 1, v1: 0.25 },
  sand: { u0: 0, v0: 0.25, u1: 0.25, v1: 0.5 },
  log_side: { u0: 0.25, v0: 0.25, u1: 0.5, v1: 0.5 },
  log_top: { u0: 0.5, v0: 0.25, u1: 0.75, v1: 0.5 },
  leaves: { u0: 0.75, v0: 0.25, u1: 1, v1: 0.5 },
  crystal_shard: { u0: 0, v0: 0.5, u1: 0.25, v1: 0.75 },
  planks: { u0: 0.25, v0: 0.5, u1: 0.5, v1: 0.75 },
  crafting_table_top: { u0: 0.5, v0: 0.5, u1: 0.75, v1: 0.75 },
  crafting_table_side: { u0: 0.75, v0: 0.5, u1: 1, v1: 0.75 },
  furnace_top: { u0: 0, v0: 0.75, u1: 0.25, v1: 1 },
  furnace_side: { u0: 0.25, v0: 0.75, u1: 0.5, v1: 1 },
};
